### PR TITLE
Add fingerprint to soft timeouts in Celery

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hmm, why is this much different than what @tkaemming attempted to do with https://github.com/getsentry/sentry/pull/2415/files? I don't remember why that didn't work out well. I just know it needed to be reverted.

**Comment by tkaemming** [comment]
This is why I write those verbose commit messages: getsentry/sentry@1a818cedc95e53f671d46c21d0c19aad79f5ee06

> This had no effect, since `SoftTimeLimitExceeded` exceptions were being caught and logged by `sentry.utils.safe.safe_execute` without being reraised.

**Comment by dcramer** [comment]
@mattrobenolt this helps everyone not just Sentry, and we can improve the situation on our end (not everything is wrapped in safe_execute)

**Comment by mattrobenolt** [comment]
Sorry, I meant, it _didn't_ solve our issue.

**Pull request merged**
