### PR TITLE
lets try using the container based infrastructure

### PR DESCRIPTION
**Pull request by joshk**

### CODE REVIEW

**Comment by dcramer** [comment]
this will fail due to a sudo call:

```
sudo apt-get install libevent-dev
```

**Comment by joshk** [comment]
Yep, give me a day, I'll get this to work :)

**Comment by dcramer** [comment]
Looks to work. Thanks!

**Comment by joshk** [comment]
Oh, awesome, well, I was also going to send a PR to change to using Travis for caching but wanted to check with you first what dirs you need to cache?

**Comment by dcramer** [comment]
Will push up some changes for it. Is there a recommended way to cache $VIRTUAL_ENV? Can we use env vars in the cache directories?

**Comment by joshk** [comment]
I see you are 10 steps ahead of me!
What do you want to cache in $VIRTUAL_ENV?

**Comment by dcramer** [comment]
@joshk possibly the whole thing

**Comment by joshk** [comment]
Is there a particular reason you want to cache the entire VirtualEnv? I think this will explode the cache and not really improve anything, I mean, you are already at 1-2min test runs.

**Comment by dcramer** [comment]
Thats fair. Going to ignore it for now.

**Pull request merged**
