### PR TITLE
Added config option for celery handler's logging level.

### PR DESCRIPTION
**Pull request by maciej-gol**

### CODE REVIEW

**Comment by xordoquy** [comment]
I would welcome a short addition to the documentation to merge this.
I restarted the travis build, seems the build fails because it had some networking issues.

**Comment by maciej-gol** [comment]
@xordoquy sure, will do!
Regarding the failed build - yeah, I've checked it this morning to see some strange failures but I've soon got focused on something else and didn't poke anyone about this.

**Comment by xordoquy** [comment]
Well, regarding the build, it looks like there wasn't much to do on your side, it's all green now \o/

**Comment by maciej-gol** [comment]
@xordoquy I've pushed my changes to the docs, but the Travis build failed once again with similar error - this time only for `Django==1.6.10` :-/

**Comment by xordoquy** [comment]
Thanks for the pull request !

**Comment by PonderingGrower** [comment]
I would love to see this in the next release. I've speend almost two days trying to work around the lack of this option and failed completely.

**Pull request merged**
