### PR TITLE
Travis deployments

### PR DESCRIPTION
**Pull request by ashwoods**
Deployments to pypi on pushed git tags

### CODE REVIEW

**Comment by ashwoods** [comment]
hmm, maybe I should test first with another script. I might have to add another stage with a condition.

**Comment by ashwoods** [comment]
No need for conditions on its own stage.

**Comment by ashwoods** [comment]
Damn, travis is always tricky. @dcramer the current config with build stages works ok.

**Comment by mitsuhiko** [comment]
@ashwoods I'm good with this however I would propose to pass `--format=zip` to bdist_wheel to make windows users a bit more happy.

**Comment by ashwoods** [comment]
@mitsuhiko I guess you meant to sdist right? afaik isn't wheel always a zip?

**Comment by mitsuhiko** [comment]
Sorry yes, i mean sdist.

**Pull request merged**
