### PR TITLE
Replace obsolete web client in Twisted transport

### PR DESCRIPTION
**Pull request by hynek**
Raven currently uses an obsolete API to do its HTTP(S) requests.

Using the “new” Agent API adds the following features:

1. Certificate and hostname validation (current implementation is MITMable).
2. A persistent HTTP pool.

I’m not sure how much of a deal 1. is WRT to backward-compatibility (people are known to run broken TLS setups after all).

I would have written tests but turns out, that Raven has no tests for its Twisted transport.  FWIW, there’s a py.test plugin to run Twisted tests: https://pypi.python.org/pypi/pytest-twisted/ but I’m not sure if you want to add it to your suite.

### CODE REVIEW

**Comment by xordoquy** [comment]
Thanks for the PR.
I'll likely split the various integration part away from raven later. I'll probably consider pytest-twisted once it's removed from the "core".
I'll try to take some time next week to review this.

**Comment by hynek** [comment]
Oh, will the integrations be even plugable? (maybe they already are, didn’t look too closely D:)

**Comment by xordoquy** [comment]
they should remain as they are, they will just be part of another package. This will allow better build matrixes since the current one is only against Django

**Comment by hynek** [comment]
I’ve tweaked it a little bit, feel free to ask any questions about it general or Twisted in particular.

BTW, I’m pretty sure the UDP transport is broken (where is `twisted.internet.reactor.listenUDP` supposed to come from?).

**Comment by xordoquy** [comment]
@hynek the UDP protocole will be dropped any time soon.

**Comment by xordoquy** [comment]
By the way, do you know when/since what version the new agent API is available ?

**Comment by hynek** [comment]
9.0, so it should be from 2009.

BTW, I just read that  raven transports should support timeout, verify_ssl, and ca_certs.  The current transport supports none of them but since those changes start verifying ssl, I guess support for it should be added before merging?

**Comment by xordoquy** [comment]
@hynek most transport don't support verify_sll and ca_cert yet. Feel free to add it now or later.

**Comment by xordoquy** [comment]
Thanks for the PR !

**Pull request merged**
