### PR TITLE
Update to latest flake8 and use pycodestyle

### PR DESCRIPTION
**Pull request by felixonmars**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-python/798)

### CODE REVIEW

**Comment by dcramer** [comment]
@getsentry/python

**Comment by dcramer** [comment]
Whats the difference between pep8 and pycodestyle? Is it just that new flake8 switched to using it?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-python/798#-:-KMAxA951CQ4MRdlZUXt:413800973)*

**Comment by felixonmars** [comment]
It's a rename upstream, and new flake8 switched to use the new name.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-python/798#-:-KMCXO8oOdspNX_g4OtJ:-639799171)*

**Comment by dcramer** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-python/798)*

**Pull request merged**
