### PR TITLE
Allow logging exclusions during object creation and `init_app`

### PR DESCRIPTION
**Pull request by radzinzki**
Hi there! 

This PR would allow the passage of a logging exclusions to the logging setup during the creation of the `Sentry` object or while calling `init_app`. Something like:

```python
sentry_object = Sentry(..., logging=True, logging_exclusions=("logger1", "logger2", ...))
```

This in turn would call the `setup_logging` like so:

```python
setup_logging(SentryHandler(self.client, level=self.level), exclude=the_passed_tuple)
```

Would you folks be open to something like this? If so, then i could go ahead and write some tests or clean this up a little bit.

### CODE REVIEW

**Comment by mitsuhiko** [comment]
I think I'm okay with adding this if there are tests and documentation for it.

**Comment by radzinzki** [comment]
Alright then, I'll get to it.

**Comment by radzinzki** [comment]
I've added tests and some documentation. How does this look now?

/cc @mitsuhiko

**Comment by mitsuhiko** [comment]
Awesome, thanks!

**Pull request merged**
