### PR TITLE
Add last_event_id to Client

### PR DESCRIPTION
**Pull request by dcramer**

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Looks good but I swear we already had that. Am I imagining things?

**Comment by dcramer** [comment]
@mitsuhiko only in Flask afaict

**Comment by mitsuhiko** [comment]
I guess we should make the Flask client also set that attribute in addition to the version on `g`.

**Comment by mitsuhiko** [comment]
Not here though: https://github.com/getsentry/raven-python/blob/40b368e2ec1c245141414343d7c4d51a5aca85c1/raven/contrib/flask.py#L116-L130

**Comment by dcramer** [comment]
@mitsuhiko that calls out to capture which does it. We dont use the same last_event_id since the behavior here differs and resets on each request

**Pull request merged**
