### PR TITLE
Fix syntax error under 2.7

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by xordoquy** [comment]
I'm not sure this is equivalent. @dcramer thoughs ?

**Comment by josegonzalez** [comment]
What was the * supposed to be doing? I've never seen that operator on it's own within a function declaration.

**Comment by xordoquy** [comment]
I'd assume it's for positional arguments before keywords ones. Related to the new unpacking PEP 448 though the document doesn't mention this.

**Comment by asvetlov** [comment]
Please no. It's python 3 syntax, the module is not intended to work on python 2 (asyncio and aiohttp are python3-only libraries).
Regarding to syntax warning (I assume that's the source of proposed changes) please take a look on `yield from` expression also.

Yes, you can get rid of keyword-only arguments but cannot drop or replace `yield from`

**Comment by josegonzalez** [comment]
Poop, I was hoping to avoid the syntax error during install. Guess I'll close this then.

**Pull request closed without merging**
