### PR TITLE
Fix behavior of raven command on Django 1.8+

### PR DESCRIPTION
**Pull request by dcramer**
Fixes GH-818

This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-python/824)

### CODE REVIEW

**Comment by fengsi** [comment]
Tested but seems not working?
```
$ python manage.py raven
Usage: manage.py raven test
```
```
$ python manage.py raven test
usage: manage.py raven [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                       [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                       [--data DATA] [--tags TAGS]
manage.py raven: error: unrecognized arguments: test
```

**Comment by dcramer** [comment]
Doh. I guess our unit test is totally wrong.

**Comment by fengsi** [comment]
Looks so...
https://github.com/getsentry/raven-python/blob/master/tests/contrib/django/management/commands/test_raven.py#L17
`command` is passed in test manually resulting in `command` is always there but `add_arguments()` knows nothing about `test`...

And for `def handle(self, *args, **options):` the arg should be in `**options`.

I did a quick hack by adding a positional `test` arg, but it doesn't look consistent with previous message (also it's required to check "test" string for `test` arg, which is weird):
```
usage: manage.py raven [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                       [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                       [--data DATA] [--tags TAGS]
                       test
manage.py raven: error: the following arguments are required: test
```
BTW could we replace `print()` with `self.stderr.write()`?

**Comment by dcramer** [comment]
This shoudl be fixed in 5.24.3.

Re: sys.stderr.write, I'm not opposed, but I dont care enough to go make the change at this point

**Pull request merged**
