### PR TITLE
Add support to 'application/json' Content-Type when reporting to Sentry

### PR DESCRIPTION
**Pull request by RobGThai**
I had this patch in my child class to report JSON to Sentry. Thought it would be useful to have it support inside the Sentry class itself.

### CODE REVIEW

**Comment by dcramer** [comment]
Is request.data a common thing or is that specific to something like django-rest-framework?

**Comment by RobGThai** [comment]
I'm using Flask, so I don't think it's specific to Django. Might be REST-api-framework though.

**Comment by dcramer** [comment]
Doh, I totally didn't pay attention to the file changed here

**Comment by mitsuhiko** [comment]
One thing I would change is this:

```python
        headers = dict(get_headers(request.environ))
        if self.is_json_type(headers['Content-Type']):
```

That makes no sense in Flask, there is already a better way to get the mimetype (that's the content type without parameters):

```python
        if self.is_json_type(request.mimetype):
```

**Comment by RobGThai** [comment]
@mitsuhiko Thanks, I'm pretty new to Python so I didn't realise there's that option :bow: 

Updated.

**Comment by dcramer** [comment]
Thanks!

**Comment by mitsuhiko** [comment]
The default value to the function won't work.  It will be an unbound function.  Just set it to `None` instead.

**Pull request merged**
