### PR TITLE
Issue 550 exception chains

### PR DESCRIPTION
**Pull request by cjerdonek**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-python/811)

### CODE REVIEW

**Comment by dcramer** [comment]
@getsentry/python

**Comment by dcramer** [comment]
This is great, thanks!

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-python/811#-:-KNY1z6m-Gw0Rsh9-2-w:-970016080)*

**Comment by cjerdonek** [comment]
Awesome, thanks!

**Comment by jstasiak** [comment]
This is awesome, thanks a lot. Is there a chance it's released on PyPI any time soon?

**Pull request merged**
