### PR TITLE
Adding framework name to sdk name

### PR DESCRIPTION
**Pull request by ehfeng**
Doing this for Flask to see if this is the right pattern. I'll fill this in for the rest of the frameworks. This is tied with the FeatureAdoption https://github.com/getsentry/sentry/pull/5481, to track what frameworks are being used.

### CODE REVIEW

**Comment by bretthoerner** [comment]
Sentry side: https://github.com/getsentry/sentry/pull/5517

**Comment by ehfeng** [comment]
@bretthoerner is it cool if i just complete this PR to add the new "integration" field? just checking in case there's anything I've forgotten. Also, @MaxBittker was asking if there's a canonical list of all platforms/integrations that I should be grabbing strings from.

**Comment by bretthoerner** [comment]
Yeah, `integrations` in the `sdk` object is now valid and takes an array of strings.

There's no canonical list, it's just a "what makes sense for the language" kind of thing. Basically anything that enables special code paths in the SDK, so framework and logging integrations, I'm not sure what else?

**Comment by ehfeng** [comment]
We're changing how this works, using a `platform_id` field instead.

**Pull request closed without merging**
